### ISSUE TITLE
v4.5 API jars are still invalid

### ISSUE THREAD

**Issue by matosf** [mambu-gmbh/Mambu-APIs-Java#130]
The following are not valid jars:
Mambu-APIs-Java-4.5-bin-sources.jar
Mambu-APIs-Java-4.5-bin.jar

**Comment by acostros** [comment]
What do you mean by "not valid"?

**Comment by matosf** [comment]
They seem not to contain valid JAR structure inside (try to open them with http://jd.benow.ca/ for example).
The same is happening the mambu-models-V4.5.jar.

If we clone the repo and build it ourselves, the generated jars are fine.

**Comment by acostros** [comment]
Hi Fabio,

I've looked again over the SDK jar file and nothing looks not valid
The jar file on the github has 178 KB.
I've downloaded the decompiler you suggested and opened the jar see the attached picture.
![sdk-jar](https://cloud.githubusercontent.com/assets/18039369/23124377/49ca2b66-f775-11e6-9b48-79e40b602114.jpg)
The  jar I've loaded into the decompiler is downloaded also from github not from my local machine.
What do you see in the decompiler?

**Comment by matosf** [comment]
@acostros my mistake. I was downloading them right clicking on the jar and selection download file, instead of clicking it and then clicking the Download button.

**Comment by acostros** [comment]
Hi Fabio,

Thanks for your update, I`m happy that is working ;-)
