### ISSUE TITLE
GWT-user.jar problem

### ISSUE THREAD

**Issue by kkoziol** [mambu-gmbh/Mambu-APIs-Java#151]
Please refer to this link:
https://stackoverflow.com/questions/4700712/how-to-properly-bundle-gwt-with-my-webapp-was-why-gwt-user-1-7-0-contains-ser

GWT-user.jar contains javax.servlet classes, it is very problematic because on JEE application servers it basically shadows original javax classes and causes strange errors in runtime.
Please consider using GWT-servlet.jar or provide some information in readme.md for JEE AS users.

**Comment by acostros** [comment]
Hi Krzysiek,

Thanks for your contribution and for finding the issue and letting us know. Your suggestion is good and we'll do the change once with the next release which is planned for the end of news week.

I'll keep you posted as soon as the update is done and available in github.

**Comment by acostros** [comment]
Hi Krzysiek,

We released yesterday the v5.0 version of the SDK and it contains the update you suggested. Please give it a check and let us know if it works for you now.

**Comment by kkoziol** [comment]
Works like a charm. :)
Thanks.
