### ISSUE TITLE
v6.0 model jar name

### ISSUE THREAD

**Issue by matosf** [mambu-gmbh/Mambu-APIs-Java#160]
the name of the jar for the new v6 models is not consistent with the previous naming scheme, missing the minor version:
v4: `mambu-models-V4.6.jar`
v5: `mambu-models-V5.0.jar`
v6: `mambu-models-V6.jar`

The README also seems to expect `mambu-models-V6.0.jar`.

**Comment by acostros** [comment]
Hi Fabio,

Thanks for reaching us out and for letting us know about the inconsistency, we've renamed the models jar to be consistent with the previous versions and regenerated the SDK jar. 

Please give it a try and let us know if we can further help you.
