### ISSUE TITLE
Get logs from the library

### ISSUE THREAD

**Issue by azakordonets** [mambu-gmbh/Mambu-APIs-Java#166]
Hi, i would like to log all the calls that are made by your library in my integration tests - what is the best way to do that?  Right now, when i try to make some calls with library - i don't see any logging in the console. Is there a way i could intercept logs and append it to my logger ?

**Comment by acostros** [comment]
Hi Andrew,

The simplest way that comes into my mind right now to view the logs from SDK is to override the log level for the following classes MambuAPIFactory, RequestExecutorImpl, URLHelper using java util logging. In the project you forked from Github you can see inside logger.properties the description for each class.

**Comment by azakordonets** [comment]
Ended up making up my custom logic on logging of the request\response object.
