### ISSUE TITLE
Action Required: TLS v1.0 and v1.1 restriction support

### ISSUE THREAD

**Issue by emiguelt** [mambu-gmbh/Mambu-APIs-Java#180]
Hello All,
I would like to know if this client currently support tls v1.2, since we received an email from Mambu reporting the deprecation of tls v 1.0 and 1.1.

Thanks a lot for your help.

Best,

Edwin

**Comment by acostros** [comment]
Hi Edwin,

The SDK executed API requests using TLS 1.0, TLS 1.1 and TLS 1.2, with next version it will use only TLS 1.2.

**Comment by emiguelt** [comment]
So, I just need to use the latest version of Mambu-APIs-Java?

**Comment by acostros** [comment]
Yes, that's true, all you have to do is to use the latest SDK version. On the SDK side, the TLS change will come once with V9.0 release and the server side will come with V10.

**Comment by emiguelt** [comment]
Ok, thanks a lot!
