### ISSUE TITLE
Publish SDK & dependencies to a public maven repository

### ISSUE THREAD

**Issue by dmitrygusev** [mambu-gmbh/Mambu-APIs-Java#188]
Please, publish the SDK & model jars to Maven Central or jCenter or anything else that can be plugged into a Maven/Gradle build without checking in JARs into version control.

Right now updating the dependencies is a pain every time one need to do it.

**Comment by acostros** [comment]
Hi Dimitry,

Thanks for reaching us! 
We understand the pain you're having with updating the SDK and model dependencies.
We'll be able to publish the jars on a Maven Central repo by the mid of 2019, as we are currently focussed on other priorities.

I hope this works for you, 
Andrei Costros

**Comment by dmitrygusev** [comment]
Hi Andrei,

can you kindly tell if this is still in plans to be done by mid of 2019?

Thank you

**Comment by acostros** [comment]
Hi Dimitry,

The SDK publishing on a Maven Central didn’t pop up through our stack of priorities. 
We’re currently focusing on extending the new version of APIs ([API v2.0](https://demo.sandbox.mambu.com/apidocs/) )
Unfortunately we’re not sure that in the next period of time we’ll be able to publish it.

Regards,
Andrei Costros

**Comment by dmitrygusev** [comment]
@acostros any updates on this please?

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
