### ISSUE TITLE
Missing field in Models 8.0 & 9.0 - Transactions API - "valueDate"

### ISSUE THREAD

**Issue by BrandU** [mambu-gmbh/Mambu-APIs-Java#189]
Hi,

Please see: https://support.mambu.com/docs/loan-transactions-api - see REPAYMENT "valueDate" sample

There is no such field to be found in the models, please, could this be addressed by the core team?

Thank you.

**Comment by acostros** [comment]
Hi,

Sorry for the inconvenience, we've updated the models and created new SDK jar.
Please check v9.2 version for both SDK and models.

Andrei Costros

**Comment by BrandU** [comment]
Hi Andrei, 

Thank you for a quick reaction :-)

We've noticed that the LoanTransaction was extended by "valueDate".

However JSONTransactionRequest seems not having it and we need it here in order to be able to POST these repayments.

Could you please have a look at this as well? 

Thank you

Brano

**Comment by acostros** [comment]
Hi Brano,

I refreshed JSONTransactionRequest to also include the "valueDate" field.
Please check again the jars, you should see the v9.3 for both models and SDK.

Thanks for spotting the missing field!
Please let me know if there is anything I can help you with ;)

Andrei Costros

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
