### ISSUE TITLE
SDK Settings - request "retry" policy?

### ISSUE THREAD

**Issue by BrandU** [mambu-gmbh/Mambu-APIs-Java#192]
Hi guys,

Is there a possibility to configure some sort of a retry policy when using the SDK, we are experiencing connectivity issues from time to time.

Thanks :-)

**Comment by acostros** [comment]
Hi, 

Thanks for using our SDK and for reaching out to us.
There is no retry mechanism in the SDK, therefore no policy to be configured. 
Each SDK client may create his own retry mechanism.

**Comment by techdot** [comment]
@BrandU We implemented a queue based retry solution (Ex: AWS SQS) for some of the Mambu clients we work with. Happy to discuss if you need any additional info!

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
