### ISSUE TITLE
More transaction types not supported

### ISSUE THREAD

**Issue by metalpalo** [mambu-gmbh/Mambu-APIs-Java#193]
Hi guys,
we use version 9.3.

Is possible to extend LoanService.executeJSONTransactionRequest with another transaction types?
Concretly, for this moment we need to execute transaction with type LoanTransactionType.INTEREST_APPLIED. 
When looking at this method we see that only five ones are supported: 
DISBURSMENT,FEE,REPAYMENT,INTEREST_RATE_CHANGED,PAYMENT_MADE

thanks

**Comment by acostros** [comment]
Hi 

We have a convenience method that you can use in order to achieve the same thing. 
See applyInterestToLoanAccount from LoanService.

I hope this helps, if not please let me know.

Andrei Costros

**Comment by metalpalo** [comment]
Hi Andrei,

yes probably we could use this one for INTEREST_APPLIED. 
But we will appreciate one general method to accept all transaction types defined in com.mambu.loans.shared.model.LoanTransactionType which mostly matching the ones defined in
https://support.mambu.com/docs/loan-transactions-api#post-transactions

I don't know if there are some reasons to restrict only to five ones but it would be great to has something general. 

As another option for us would be exposinog serviceExecutor via getter to handle this.

thanks
br palo

**Comment by acostros** [comment]
Hi Palo,

The reason we have dedicated method for INTEREST_APPLIED transactions is to have a convenience method that requires only the needed params instead of have a generic one requiring generic param (object) to be set differently based on the transaction type you want to create.
We'll update the generic method to support INTEREST_APPLIED and we'll do patch by the beginning of the next week. Therefore you'll be able to use the generic method.

I hope this helps, please let me know if not.

Regards, 
Andrei Costros

**Comment by acostros** [comment]
Hi Palo, 

We've extended executeJSONTransactionRequest() method to support INTEREST_APPLIED, new SDK version was added on master branch. 
Please give it a try and let us know whether works for you or not.

Regards,
Andrei Costros

**Comment by metalpalo** [comment]
Hi Andrei,

it should be good fo us for now. But for the future we will appreciate one general method to accept all transaction types as I wrote 25 days ago, not only restricted for six ones as today. 
I understood that you will implement it by this way, or not?
Is possible to expect something like this?

thanks
brpalo

**Comment by acostros** [comment]
Hi Palo,

We'll use request based approach to enable more transaction types through the generic method.
We'll analyse each case separately.

Regards, 
Andrei Costros

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
