### ISSUE TITLE
Missing fields - /api/loanproducts/{ID}/schedule/

### ISSUE THREAD

**Issue by BrandU** [mambu-gmbh/Mambu-APIs-Java#200]
Hi,

See: https://support.mambu.com/docs/loan-products-api

We've noticed that it's not possible to populate all query attributes using the SDK when calling the repayment schedule, missing fields:

- periodicPayment,
- organizationCommission.

Could you please add those? It seems that we need to have the LoanAccount extended.

Thank you.

Brano.

**Comment by acostros** [comment]
Hi Brano,

We`ve extended the SDK to support sending of "periodicPayment","organizationCommission"  query params. Please see the overloaded getLoanProductSchedule(String productId, LoanAccount account, ScheduleQueryParams queryParams) method from LoanService.
Also as usage example you may see previewSchedule() in DemoTestLoanService.

I hope this works for you. 
Please let us know f you have any other questions.

Best regards,

Andrei Costros

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
