### ISSUE TITLE
please add new method into ClientService new method getClientByDocId

### ISSUE THREAD

**Issue by Srso** [mambu-gmbh/Mambu-APIs-Java#203]
Hi, it's possible add new method, only get client by document id (last name can by after some time changed, e.g. wrongly written) 

public List<Client> getClientByDocId(String documentId) throws MambuApiException {...

https://github.com/mambu-gmbh/Mambu-APIs-Java/blob/43136b82645e42e76fa2a25049f6098d099ee12c/src/com/mambu/apisdk/services/ClientsService.java#L230

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
