### ISSUE TITLE
Add USER, Branch and CENTRE support to SearchService

### ISSUE THREAD

**Issue by techdot** [mambu-gmbh/Mambu-APIs-Java#206]
Search API https://support.mambu.com/docs/objects-search-api does seem to USER objects but API wrapper doesn't. Is it possible to support USER, BRANCH and CENTRE types
Ref: https://github.com/mambu-gmbh/Mambu-APIs-Java/blob/6c2c2ada378853a1e38b9b49358e563dd4ba3d17/src/com/mambu/apisdk/services/SearchService.java#L296

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
