### ISSUE TITLE
Make Mambu API Factory Multi-Tenant Capable

### ISSUE THREAD

**Issue by thobach** [mambu-gmbh/Mambu-APIs-Java#30]
The MambuAPIFactory is implemented as a singleton which makes it hard to use in multi-tenant applications.

A new factory class is needed with a factory method that returns a tenant-specific factory instance which binds a new MambuAPIModule (with the tenant-specific credentials) for every tenant, instead of calling a setup method, which sets the credentials globally in the singleton MambuAPIFactory.

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
