### ISSUE TITLE
setAssignedBranchKey not working

### ISSUE THREAD

**Issue by IrakliCharkhalashvili** [mambu-gmbh/Mambu-APIs-Java#32]
Hello,
I'm using 3.6 libraries and this functionality is not working:

 MambuAPIFactory.setUp("kapiltd.sandbox.mambu.com", "username", "Password");
 Client client = MambuAPIFactory.getClientService().getClient("771159790");

client.setAssignedBranchKey("8a2ac5c747a4c7050147a67dff453f40");
client.setAssignedUserKey("8ada716a44aaa3040144aac7897e0020");

setAssignedBranchKey and setAssignedUserKey are not working

**Comment by georgeghimici** [comment]
Hello!

Unfortunately this repository will be archived because it won't  be maintained anymore with new functionality and security updates. Main source of documentation  and specifications for API will remain https://api.mambu.com/.

Cheers,
George.
