### ISSUE TITLE
Making sources available in build folder

### ISSUE THREAD

**Issue by techdot** [mambu-gmbh/Mambu-APIs-Java#82]
Hi Guys,

Currently when you build the application it generates a sources.jar in the target folder (ex: Mambu-APIs-Java-4.3-bin-sources.jar), could you make this available in build folder every time a new version is released please. 

Most of the IDEs decompile class files so we might actually don't need the sources, but the problem is when you want to search for certain string in libraries they just ignore the libraries those don't have sources attached (explicitly)!

Thanks

**Comment by acostros** [comment]
Hi,

Sure, we'll make the jar sources available, in the build folder, beginning with the 4.3 version. 

All the best,
Andrei

**Comment by techdot** [comment]
Thanks. Very much appreciate it.

-Bharat

**Comment by acostros** [comment]
The sources for v4.3 have been released, please check the build folder. Closing this issue.
